//设置地址信息（市）
const SET_ADDRESS='SET_CITY_ADDRESS'
//初始化地址
const DESTORY_ADDRESS='CHANGE_ADDRESS'
// 设置 session
const SET_SESSION = "SET_TOKEN";
// 销毁会话
const DESTROY_SESSION = "DESTROY_SESSION";
//设置用户信息
const SET_USERMESSAGE="SET_USERMEG"
//初始化用户信息
const INIT_USERMESSAGE="INIT_USERMEG"

export {SET_ADDRESS,DESTORY_ADDRESS,SET_SESSION, DESTROY_SESSION,
    SET_USERMESSAGE, INIT_USERMESSAGE}
export default {SET_ADDRESS,DESTORY_ADDRESS,SET_SESSION, DESTROY_SESSION,
    SET_USERMESSAGE , INIT_USERMESSAGE }